[env:esp32-s3-devkitc-1]
platform = espressif32@~6.13.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

# Set 8MB of Flash
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

# Set Quad SPI for Flash (qio) and Octal SPI for 8MB PSRAM (opi)
board_build.arduino.memory_type = qio_opi

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM